// from https://en.wikipedia.org/wiki/List_of_Wikipedias
var wikis = [
['Abkhazian', 'Аҧсшәа', 'ab'],
['Acehnese', 'Acèh', 'ace'],
['Afrikaans', 'Afrikaans', 'af'],
['Akan', 'Akan', 'ak'],
['Albanian', 'shqip', 'sq'],
['Alemannic', 'Alemannisch', 'als'],
['Amharic', 'አማርኛ', 'am'],
['Anglo-Saxon', 'Ænglisc', 'ang'],
['Arabic', 'العربية', 'ar'],
['Aragonese', 'aragonés', 'an'],
['Aramaic', 'ܐܪܡܝܐ', 'arc'],
['Armenian', 'Հայերեն', 'hy'],
['Aromanian', 'armãneashti', 'roa-rup'],
['Assamese', 'অসমীয়া', 'as'],
['Asturian', 'asturianu', 'ast'],
['Avar', 'авар', 'av'],
['Aymara', 'Aymar aru', 'ay'],
['Azerbaijani', 'azərbaycanca', 'az'],
['Bambara', 'bamanankan', 'bm'],
['Banjar', 'Bahasa Banjar', 'bjn'],
['Banyumasan', 'Basa Banyumasan', 'map-bms'],
['Bashkir', 'башҡортса', 'ba'],
['Basque', 'euskara', 'eu'],
['Bavarian', 'Boarisch', 'bar'],
['Belarusian', 'беларуская', 'be'],
['Belarusian (Taraškievica)', 'беларуская (тарашкевіца)‎', 'be-tarask'],
['Bengali', 'বাংলা', 'bn'],
['Bihari', 'भोजपुरी', 'bh'],
['Bishnupriya Manipuri', 'বিষ্ণুপ্রিয়া মণিপুরী', 'bpy'],
['Bislama', 'Bislama', 'bi'],
['Bosnian', 'bosanski', 'bs'],
['Breton', 'brezhoneg', 'br'],
['Buginese', 'ᨅᨔ ᨕᨘᨁᨗ', 'bug'],
['Bulgarian', 'български', 'bg'],
['Burmese', 'မြန်မာဘာသာ', 'my'],
['Buryat', 'буряад', 'bxr'],
['Cantonese', '粵語', 'zh-yue'],
['Catalan', 'català', 'ca'],
['Cebuano', 'Cebuano', 'ceb'],
['Central Bicolano', 'Bikol Central', 'bcl'],
['Chamorro', 'Chamoru', 'ch'],
['Chavacano', 'Chavacano de Zamboanga', 'cbk-zam'],
['Chechen', 'нохчийн', 'ce'],
['Cherokee', 'ᏣᎳᎩ', 'chr'],
['Cheyenne', 'Tsetsêhestâhese', 'chy'],
['Chichewa', 'Chi-Chewa', 'ny'],
['Chinese', '中文', 'zh'],
['Chuvash', 'Чӑвашла', 'cv'],
['Classical Chinese', '文言', 'zh-classical'],
['Cornish', 'kernowek', 'kw'],
['Corsican', 'corsu', 'co'],
['Cree', 'Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ', 'cr'],
['Crimean Tatar', 'qırımtatarca', 'crh'],
['Croatian', 'hrvatski', 'hr'],
['Czech', 'čeština', 'cs'],
['Danish', 'dansk', 'da'],
['Divehi', 'ދިވެހިބަސް', 'dv'],
['Dutch', 'Nederlands', 'nl'],
['Dutch Low Saxon', 'Nedersaksies', 'nds-nl'],
['Dzongkha', 'ཇོང་ཁ', 'dz'],
['Egyptian Arabic', 'مصرى', 'arz'],
['Emilian-Romagnol', 'emiliàn e rumagnòl', 'eml'],
['English', 'English', 'en'],
['Erzya', 'эрзянь', 'myv'],
['Esperanto', 'Esperanto', 'eo'],
['Estonian', 'eesti', 'et'],
['Ewe', 'eʋegbe', 'ee'],
['Extremaduran', 'estremeñu', 'ext'],
['Faroese', 'føroyskt', 'fo'],
['Fiji Hindi', 'Fiji Hindi', 'hif'],
['Fijian', 'Na Vosa Vakaviti', 'fj'],
['Finnish', 'suomi', 'fi'],
['Franco-Provençal', 'arpetan', 'frp'],
['French', 'français', 'fr'],
['Friulian', 'furlan', 'fur'],
['Fula', 'Fulfulde', 'ff'],
['Gagauz', 'Gagauz', 'gag'],
['Galician', 'galego', 'gl'],
['Gan', '贛語', 'gan'],
['Georgian', 'ქართული', 'ka'],
['German', 'Deutsch', 'de'],
['Gilaki', 'گیلکی', 'glk'],
['Goan Konkani', 'गोवा कोंकणी / Gova Konknni', 'gom'],
['Gothic', '𐌲𐌿𐍄𐌹𐍃𐌺', 'got'],
['Greek', 'Ελληνικά', 'el'],
['Greenlandic', 'kalaallisut', 'kl'],
['Guarani', 'Avañe\'ẽ', 'gn'],
['Gujarati', 'ગુજરાતી', 'gu'],
['Haitian', 'Kreyòl ayisyen', 'ht'],
['Hakka', '客家語/Hak-kâ-ngî', 'hak'],
['Hausa', 'Hausa', 'ha'],
['Hawaiian', 'Hawai`i', 'haw'],
['Hebrew', 'עברית', 'he'],
['Hill Mari', 'кырык мары', 'mrj'],
['Hindi', 'हिन्दी', 'hi'],
['Hungarian', 'magyar', 'hu'],
['Icelandic', 'íslenska', 'is'],
['Ido', 'Ido', 'io'],
['Igbo', 'Igbo', 'ig'],
['Ilokano', 'Ilokano', 'ilo'],
['Indonesian', 'Bahasa Indonesia', 'id'],
['Interlingua', 'interlingua', 'ia'],
['Interlingue', 'Interlingue', 'ie'],
['Inuktitut', 'ᐃᓄᒃᑎᑐᑦ/inuktitut', 'iu'],
['Inupiak', 'Iñupiak', 'ik'],
['Irish', 'Gaeilge', 'ga'],
['Italian', 'italiano', 'it'],
['Japanese', '日本語', 'ja'],
['Javanese', 'Basa Jawa', 'jv'],
['Kabardian', 'Адыгэбзэ', 'kbd'],
['Kabyle', 'Taqbaylit', 'kab'],
['Kalmyk', 'хальмг', 'xal'],
['Kannada', 'ಕನ್ನಡ', 'kn'],
['Kapampangan', 'Kapampangan', 'pam'],
['Karachay-Balkar', 'къарачай-малкъар', 'krc'],
['Karakalpak', 'Qaraqalpaqsha', 'kaa'],
['Kashmiri', 'कॉशुर / کٲشُر', 'ks'],
['Kashubian', 'kaszëbsczi', 'csb'],
['Kazakh', 'қазақша', 'kk'],
['Khmer', 'ភាសាខ្មែរ', 'km'],
['Kikuyu', 'Gĩkũyũ', 'ki'],
['Kinyarwanda', 'Kinyarwanda', 'rw'],
['Kirghiz', 'Кыргызча', 'ky'],
['Kirundi', 'Kirundi', 'rn'],
['Komi', 'коми', 'kv'],
['Komi-Permyak', 'Перем Коми', 'koi'],
['Kongo', 'Kongo', 'kg'],
['Korean', '한국어', 'ko'],
['Kurdish', 'Kurdî', 'ku'],
['Ladino', 'Ladino', 'lad'],
['Lak', 'лакку', 'lbe'],
['Lao', 'ລາວ', 'lo'],
['Latgalian', 'latgaļu', 'ltg'],
['Latin', 'Latina', 'la'],
['Latvian', 'latviešu', 'lv'],
['Lezgian', 'лезги', 'lez'],
['Ligurian', 'Ligure', 'lij'],
['Limburgish', 'Limburgs', 'li'],
['Lingala', 'lingála', 'ln'],
['Lithuanian', 'lietuvių', 'lt'],
['Lojban', 'Lojban', 'jbo'],
['Lombard', 'lumbaart', 'lmo'],
['Low Saxon', 'Plattdüütsch', 'nds'],
['Lower Sorbian', 'dolnoserbski', 'dsb'],
['Luganda', 'Luganda', 'lg'],
['Luxembourgish', 'Lëtzebuergesch', 'lb'],
['Macedonian', 'македонски', 'mk'],
['Maithili', 'मैथिली', 'mai'],
['Malagasy', 'Malagasy', 'mg'],
['Malay', 'Bahasa Melayu', 'ms'],
['Malayalam', 'മലയാളം', 'ml'],
['Maltese', 'Malti', 'mt'],
['Manx', 'Gaelg', 'gv'],
['Maori', 'Māori', 'mi'],
['Marathi', 'मराठी', 'mr'],
['Mazandarani', 'مازِرونی', 'mzn'],
['Meadow Mari', 'олык марий', 'mhr'],
['Min Dong', 'Mìng-dĕ̤ng-ngṳ̄', 'cdo'],
['Min Nan', 'Bân-lâm-gú', 'zh-min-nan'],
['Minangkabau', 'Baso Minangkabau', 'min'],
['Mingrelian', 'მარგალური', 'xmf'],
['Mirandese', 'Mirandés', 'mwl'],
['Moksha', 'мокшень', 'mdf'],
['Mongolian', 'монгол', 'mn'],
['Nahuatl', 'Nāhuatl', 'nah'],
['Nauruan', 'Dorerin Naoero', 'na'],
['Navajo', 'Diné bizaad', 'nv'],
['Neapolitan', 'Napulitano', 'nap'],
['Nepali', 'नेपाली', 'ne'],
['Newar', 'नेपाल भाषा', 'new'],
['Norfolk', 'Norfuk / Pitkern', 'pih'],
['Norman', 'Nouormand', 'nrm'],
['North Frisian', 'Nordfriisk', 'frr'],
['Northern Luri', 'لۊری شومالی', 'lrc'],
['Northern Sami', 'sámegiella', 'se'],
['Northern Sotho', 'Sesotho sa Leboa', 'nso'],
['Norwegian (Bokmål)', 'norsk bokmål', 'no'],
['Norwegian (Nynorsk)', 'norsk nynorsk', 'nn'],
['Novial', 'Novial', 'nov'],
['Occitan', 'occitan', 'oc'],
['Old Church Slavonic', 'словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ', 'cu'],
['Oriya', 'ଓଡ଼ିଆ', 'or'],
['Oromo', 'Oromoo', 'om'],
['Ossetian', 'Ирон', 'os'],
['Palatinate German', 'Pälzisch', 'pfl'],
['Pali', 'पालि', 'pi'],
['Pangasinan', 'Pangasinan', 'pag'],
['Papiamentu', 'Papiamentu', 'pap'],
['Pashto', 'پښتو', 'ps'],
['Pennsylvania German', 'Deitsch', 'pdc'],
['Persian', 'فارسی', 'fa'],
['Picard', 'Picard', 'pcd'],
['Piedmontese', 'Piemontèis', 'pms'],
['Polish', 'polski', 'pl'],
['Pontic', 'Ποντιακά', 'pnt'],
['Portuguese', 'português', 'pt'],
['Punjabi', 'ਪੰਜਾਬੀ', 'pa'],
['Quechua', 'Runa Simi', 'qu'],
['Ripuarian', 'Ripoarisch', 'ksh'],
['Romani', 'Romani', 'rmy'],
['Romanian', 'română', 'ro'],
['Romansh', 'rumantsch', 'rm'],
['Russian', 'русский', 'ru'],
['Rusyn', 'русиньскый', 'rue'],
['Sakha', 'саха тыла', 'sah'],
['Samoan', 'Gagana Samoa', 'sm'],
['Samogitian', 'žemaitėška', 'bat-smg'],
['Sango', 'Sängö', 'sg'],
['Sanskrit', 'संस्कृतम्', 'sa'],
['Sardinian', 'sardu', 'sc'],
['Saterland Frisian', 'Seeltersk', 'stq'],
['Scots', 'Scots', 'sco'],
['Scottish Gaelic', 'Gàidhlig', 'gd'],
['Serbian', 'српски / srpski', 'sr'],
['Serbo-Croatian', 'srpskohrvatski / српскохрватски', 'sh'],
['Sesotho', 'Sesotho', 'st'],
['Shona', 'chiShona', 'sn'],
['Sicilian', 'sicilianu', 'scn'],
['Silesian', 'ślůnski', 'szl'],
['Simple English', 'Simple English', 'simple'],
['Sindhi', 'سنڌي', 'sd'],
['Sinhalese', 'සිංහල', 'si'],
['Slovak', 'slovenčina', 'sk'],
['Slovenian', 'slovenščina', 'sl'],
['Somali', 'Soomaaliga', 'so'],
['Sorani', 'کوردیی ناوەندی', 'ckb'],
['Southern Azerbaijani', 'تۆرکجه', 'azb'],
['Spanish', 'español', 'es'],
['Sranan', 'Sranantongo', 'srn'],
['Sundanese', 'Basa Sunda', 'su'],
['Swahili', 'Kiswahili', 'sw'],
['Swati', 'SiSwati', 'ss'],
['Swedish', 'svenska', 'sv'],
['Tagalog', 'Tagalog', 'tl'],
['Tahitian', 'reo tahiti', 'ty'],
['Tajik', 'тоҷикӣ', 'tg'],
['Tamil', 'தமிழ்', 'ta'],
['Tarantino', 'tarandíne', 'roa-tara'],
['Tatar', 'татарча/tatarça', 'tt'],
['Telugu', 'తెలుగు', 'te'],
['Tetum', 'tetun', 'tet'],
['Thai', 'ไทย', 'th'],
['Tibetan', 'བོད་ཡིག', 'bo'],
['Tigrinya', 'ትግርኛ', 'ti'],
['Tok Pisin', 'Tok Pisin', 'tpi'],
['Tongan', 'lea faka-Tonga', 'to'],
['Tsonga', 'Xitsonga', 'ts'],
['Tswana', 'Setswana', 'tn'],
['Tumbuka', 'chiTumbuka', 'tum'],
['Turkish', 'Türkçe', 'tr'],
['Turkmen', 'Türkmençe', 'tk'],
['Tuvan', 'тыва дыл', 'tyv'],
['Twi', 'Twi', 'tw'],
['Udmurt', 'удмурт', 'udm'],
['Ukrainian', 'українська', 'uk'],
['Upper Sorbian', 'hornjoserbsce', 'hsb'],
['Urdu', 'اردو', 'ur'],
['Uyghur', 'ئۇيغۇرچە / Uyghurche', 'ug'],
['Uzbek', 'oʻzbekcha/ўзбекча', 'uz'],
['Walloon', 'walon', 'wa'],
['Waray-Waray', 'Winaray', 'war'],
['Welsh', 'Cymraeg', 'cy'],
['Venda', 'Tshivenda', 've'],
['Venetian', 'vèneto', 'vec'],
['Vepsian', 'vepsän kel’', 'vep'],
['West Flemish', 'West-Vlams', 'vls'],
['West Frisian', 'Frysk', 'fy'],
['Western Punjabi', 'پنجابی', 'pnb'],
['Vietnamese', 'Tiếng Việt', 'vi'],
['Volapük', 'Volapük', 'vo'],
['Wolof', 'Wolof', 'wo'],
['Võro', 'Võro', 'fiu-vro'],
['Wu', '吴语', 'wuu'],
['Xhosa', 'isiXhosa', 'xh'],
['Yiddish', 'ייִדיש', 'yi'],
['Yoruba', 'Yorùbá', 'yo'],
['Zazaki', 'Zazaki', 'diq'],
['Zeelandic', 'Zeêuws', 'zea'],
['Zhuang', 'Vahcuengh', 'za'],
['Zulu', 'isiZulu', 'zu']
];

var exports = module.exports = wikis;